openapi: 3.0.1
info:
  title: proto/proto/user/v1/user.proto
  version: version not set
servers:
- url: /
tags:
- name: UserService
paths:
  /user/register:
    post:
      tags:
      - UserService
      operationId: UserService_Register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1RegisterRequest'
        required: true
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1RegisterResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: body
  /user/{id}:
    get:
      tags:
      - UserService
      operationId: UserService_Get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1GetResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
    put:
      tags:
      - UserService
      operationId: UserService_Update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                birthday:
                  $ref: '#/components/schemas/typeDate'
        required: true
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1UpdateResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: body
    delete:
      tags:
      - UserService
      operationId: UserService_Terminate
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1TerminateResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
components:
  schemas:
    protobufAny:
      type: object
      properties:
        typeUrl:
          type: string
        value:
          pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
          type: string
          format: byte
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
    typeDate:
      title: |-
        Represents a whole or partial calendar date, such as a birthday. The time of
        day and time zone are either specified elsewhere or are insignificant. The
        date is relative to the Gregorian Calendar. This can represent one of the
        following:
      type: object
      properties:
        year:
          type: integer
          description: |-
            Year of the date. Must be from 1 to 9999, or 0 to specify a date without
            a year.
          format: int32
        month:
          type: integer
          description: |-
            Month of a year. Must be from 1 to 12, or 0 to specify a year without a
            month and day.
          format: int32
        day:
          type: integer
          description: |-
            Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
            to specify a year by itself or a year and month where the day isn't
            significant.
          format: int32
      description: |-
        * A full date, with non-zero year, month, and day values
        * A month and day value, with a zero year, such as an anniversary
        * A year on its own, with zero month and day values
        * A year and month value, with a zero day, such as a credit card expiration
        date

        Related types are [google.type.TimeOfDay][google.type.TimeOfDay] and
        `google.protobuf.Timestamp`.
    v1GetResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/v1User'
    v1RegisterRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        birthday:
          $ref: '#/components/schemas/typeDate'
    v1RegisterResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/v1User'
    v1TerminateResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/v1User'
    v1UpdateResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/v1User'
    v1User:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        birthday:
          $ref: '#/components/schemas/typeDate'
        age:
          type: string
          format: int64
